title: Tatva
description: A blog
url: "https://tatva.sumityadav.com.np"
baseurl: ""

# Build settings
markdown: CommonMark
highlighter: none
permalink: /posts/:year/:month/:day/:title/

# Site settings
author:
  name: Sumit Yadav
  email: rockerritesh4@gmail.com
  title: Research Scientist & Developer
  location: Nepal
  bio: "AI/ML researcher passionate about building intelligent systems and exploring the intersection of technology and human creativity."
  github: rockerritesh
  linkedin: rockerritesh
  twitter: rocker_ritesh
  google_scholar: https://scholar.google.com/citations?user=ag74ytsAAAAJ&hl=en
  website: https://sumityadav.com.np

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default" 