name: Build and Deploy to Docs Folder

on:
  push:
    branches: [ main ]
    paths: 
      - 'posts/**/*.md'
      - 'info/**/*.md'
      - 'src/**'
      - 'scripts/**'
      - '.github/workflows/**'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Copy markdown files to src
      run: |
        # Copy posts to src/posts if they exist
        if [ -d "posts" ] && [ "$(ls -A posts 2>/dev/null)" ]; then
          mkdir -p src/posts
          cp posts/*.md src/posts/ 2>/dev/null || true
        fi
        
        # Copy info files to src/info if they exist  
        if [ -d "info" ] && [ "$(ls -A info 2>/dev/null)" ]; then
          mkdir -p src/info
          cp info/*.md src/info/ 2>/dev/null || true
        fi
      
    - name: Generate static HTML files
      run: npm run build:static
      
    - name: Build with Vite to docs folder  
      run: npm run build
      
    - name: Commit and push built files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-build: Update static files [skip ci]"
          git push 